@startuml character


package character{
    class Character{
        -clock : Clock
        -currentAction : Action
        -currentActionStarted : Time
        -properties : Map<String, String>
        -location : Location
        +update()
    }

}

Character "1" *-- Schedule
Character "1" *-- Map

Action ..> Character
Character ..> Action
Character ..> Location

@enduml