@startuml

package core {

    class Property {
        name: String
        value: String
    }

    class Entity {}

    interface Selector {
        +isMatch(Entity: entity)
    }

    interface Actor {
        +do()
    }

}


Entity *-- Property: properties
Selector ..> Entity

@enduml