@startuml main
skinparam linetype ortho

package sandbox {
    !include target.puml
    !include action.puml

    !include schedule.puml

    !include location.puml

    !include character.puml

    !include world.puml
}




@endumls